### ISSUE TITLE
docker page not found

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/ABACBS2020_tidytranscriptomics#15]
@mblue9 I don't understand why the docker webpage is not found 

https://hub.docker.com/r/stemangiola/ABACBS2020_tidytranscriptomics

IS docker supposed to create itself automatically or I have to do do something myself

**Comment by mblue9** [comment]
So this seems to be due to the docker case sensitivity issue I mentioned, it complained about the uppercase in our repo name so I had to change the name to lowercase in the GitHub actions file and so it is here https://hub.docker.com/r/stemangiola/abacbs2020_tidytranscriptomics

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stemangiola** [comment]
Thanks I have updated the README
